#!/bin/sh
# meant to be called from cron every minute or so

LOCK='/home/ghz/shelly/shelly.lock'
WT_DIR='/home/ghz/repos/weather_tools'
DAT_DIR='/home/ghz/shelly/data'
TSY="$(date -u "+%Y")"
TSD="$(date -u "+%F")"
DEST="/home/ghz/shelly/data/${TSY}"

[ -e "${LOCK}" ] && {
        echo "$0: lock exists" | logger
                exit 1
}

wdl() {
	# Wget DownLoad so i can change options in one place
	# -t: retries [count]
	# -T: network timeout [s]
	wget -t 2 -T 6 -qO - "${@}"
}

touch "${LOCK}"

[ -d "${DEST}" ] || mkdir -p "${DEST}"

(
	date -u "+%FT%T%Z"
	wdl "http://plantlight/rpc/Shelly.GetStatus" \
	| jq | egrep 'tC|apower|voltage|current'
) | xargs echo >> "${DEST}/plantlight.${TSD}"

(
	date -u "+%FT%T%Z"
	wdl "http://bklight/rpc/Shelly.GetStatus" \
	| jq | egrep 'tC|apower|voltage|current'
) | xargs echo >> "${DEST}/bklight.${TSD}"

(
	date -u "+%FT%T%Z"
	wdl "http://pprobe-000/rpc/Shelly.GetStatus" \
	| jq | egrep 'apower|voltage|current|freq'
) | xargs echo >> "${DEST}/pprobe-000.${TSD}"

(
	date -u "+%FT%T%Z"
	wdl "http://pprobe-001/rpc/Shelly.GetStatus" \
	| jq | egrep 'apower|voltage|current|freq'
) | xargs echo >> "${DEST}/pprobe-001.${TSD}"

(
	date -u "+%FT%T%Z"
	wdl "http://pprobe-002/rpc/Shelly.GetStatus" \
	| jq | egrep 'apower|voltage|current|freq'
) | xargs echo >> "${DEST}/pprobe-002.${TSD}"

(
	date -u "+%FT%T%Z"
	wdl "http://pprobe-003/rpc/Shelly.GetStatus" \
	| jq | egrep 'apower|voltage|current|freq'
) | xargs echo >> "${DEST}/pprobe-003.${TSD}"

(
	date -u "+%FT%T%Z"
	wdl "http://pprobe-004/rpc/Shelly.GetStatus" \
	| jq | egrep 'apower|voltage|current|freq'
) | xargs echo >> "${DEST}/pprobe-004.${TSD}"

"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f plantlight
"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f bklight
"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f pprobe-000
"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f pprobe-001
"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f pprobe-002
"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f pprobe-003
"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f pprobe-004

gnuplot /home/ghz/shelly/shelly.gnuplot

/usr/local/bin/rsync -ur --delete --timeout=50 \
	--exclude .git --exclude shelly.lock -e 'ssh -q' \
	/home/ghz/shelly/ wxs:/wx0/shelly/

rm "${LOCK}"
