#!/bin/sh
# meant to be called from cron every minute or so

LOCK='/home/ghz/shelly/shelly.lock'
WT_DIR='/home/ghz/repos/weather_tools'
DAT_DIR='/home/ghz/shelly/data'
TSY="$(date -u "+%Y")"
TSD="$(date -u "+%F")"
DEST="/home/ghz/shelly/data/${TSY}"
TOT_E="${DAT_DIR}/total_energy"
TOT_E45="${DAT_DIR}/total_energy.45_days"

[ -e "${LOCK}" ] && {
        echo "$0: lock exists" | logger
                exit 1
}

wdl() {
	# Wget DownLoad so i can change options in one place
	# -t: retries [count]
	# -T: network timeout [s]
	wget -t 2 -T 6 -qO - "${@}"
}

touch "${LOCK}"

[ -d "${DEST}" ] || mkdir -p "${DEST}"

(
	date -u "+%FT%T%Z"
	wdl "http://plantlight/rpc/Shelly.GetStatus" \
	| jq | egrep 'tC|apower|voltage|current'
) | xargs echo >> "${DEST}/plantlight.${TSD}"

(
	date -u "+%FT%T%Z"
	wdl "http://bklight/rpc/Shelly.GetStatus" \
	| jq | egrep 'tC|apower|voltage|current'
) | xargs echo >> "${DEST}/bklight.${TSD}"

for i in 0 1 2 3 4 5 6; do
	(
		date -u "+%FT%T%Z"
		wdl "http://pprobe-00${i}/rpc/Shelly.GetStatus" \
		| jq | egrep 'apower|voltage|current|freq'
	) | xargs echo >> "${DEST}/pprobe-00${i}.${TSD}"

	"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f "pprobe-00${i}"
done

(
	date -u +"%FT%T%Z"
	tail -1 ${DAT_DIR}/pprobe-*.48_hours | grep "^20" | \
	awk 'BEGIN {p_sum = 0; i_sum = 0} {i_sum += $5; p_sum += $7} END {print p_sum,"W\t", i_sum, "A"}'
) | paste - - >> "${DEST}/pprobe-total.${TSD}"

"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f plantlight
"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f bklight
"${WT_DIR}/grab_n_hours" -n 48 -d "${DAT_DIR}" -f pprobe-total

# create the file if it doesn't exist. this makes first runs smoother even if it is a bit of extra work.
[ -f "${TOT_E}" ] || touch "${TOT_E}"
grep -q "${TSD}" "${TOT_E}" || echo "${TSD}" >> "${TOT_E}"
tail -45 "${TOT_E}" > "${TOT_E45}"

# the sum total energy from instantaneous minute measurements should give us
# a decent approximation of energy usage in watt * minutes.
# devide by 60 to give us watt * hour and then by 1000 to give us kWh
TOT="$(awk 'BEGIN {p_tot = 0} {p_tot += $2} END {print p_tot / 60 / 1000, "kWh"}' ${DEST}/pprobe-total.${TSD})"

# update as we go so we can watch our usage climb per day
sed -e "s/^${TSD}.*$/${TSD} ${TOT}/" -i "${TOT_E}"

gnuplot /home/ghz/shelly/shelly.gnuplot

/usr/local/bin/rsync -6ur --delete --timeout=50 \
	--exclude .git --exclude shelly.lock -e 'ssh -q' \
	/home/ghz/shelly/ wxs:/wx0/shelly/

rm "${LOCK}"
